---
title: "GraficoTema3"
output: html_document
date: "2024-03-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(plotly)
library(htmlwidgets)

# Importacion de datos
filename <- "data/owid-covid-data.csv"
datacovid <- read.csv(filename)

# Vector de paises
paises <- c("Spain", "Italy", "France", "United States", "Germany", "Canada", "Japan", "India")

# Cambiar formato de fecha
datacovid <- as.data.frame(datacovid)
datacovid$date <- as.Date(datacovid$date, format = "%Y-%m-%d")

# Seleccionar paises
covid <- subset(datacovid, location %in% paises)

# Vector de colores
colores <- c("Spain" = "red", "Italy" = "pink", "France" = "blue", "United States" = "lightgreen", "Germany" = "purple", "Canada" = "orange", "Japan" = "grey", "India" = "brown")

# Vestor de tamaños
tam <- c("Spain" = 0.7, "Italy" = 0.3, "France" = 0.3, "United States" = 0.3, "Germany" = 0.3, "Canada" = 0.3, "Japan" = 0.3, "India" = 0.3)

grafico_covid <- ggplot(covid, aes(x = date, y = new_deaths_smoothed_per_million, col= location)) +
  geom_line(aes(size = location)) + 
  scale_size_manual(values = tam) +
  scale_color_manual(values = colores) +
  labs(title = "Muertes por COVID-19 hasta la fecha actual",
       subtitle = "Las muertes confirmadas de algunos países son menores que el     número real.",
       x = "Fecha",
       y = "Muertes diarias por millón de habitantes",
       col = "País",
       size = "País", caption = "Source: [Johns Hopkins University CSSSE COVID_19 Data]") +
  theme(legend.key = element_rect(fill = "white"),
        legend.text = element_text(size = 10),
        legend.title = element_text(size = 12, face = "bold"),
        legend.margin = margin(5, 5, 5, 5)) +
  guides(col = guide_legend(override.aes = list(size = 1.5))) + 
  scale_x_date(date_labels = "%b %d, %Y") +
  theme(panel.grid.major.y = element_line("grey",size = 0.1,linetype = 2))
  


grafico_covid_interactivo <- ggplotly(grafico_covid)

# Mostrar el gráfico interactivo
grafico_covid_interactivo

# Guardar la gráfica en un archivo HTML
saveWidget(grafico_covid_interactivo, file = "graficacovid.html")

```

